#!/usr/bin/env python3
"""
gen_abi_header.py — 从 filter.h 生成 abi_expected.h

工作原理：
  1. 用 gcc -E 预处理一个包含 sizeof()/offsetof() 探测的 C 源文件
  2. 编译运行，stdout 输出 ABI 常量的数值
  3. 生成 abi_expected.h，包含这些常量的 #define

运行：
  python3 scripts/gen_abi_header.py
  输出：Core/Filter/Inc/abi_expected.h
"""

import subprocess
import sys
import os

# 探测 C 源文件：编译运行后打印所有 ABI 常量
PROBE_C = r'''
#include <stdio.h>
#include <stddef.h>
#include "filter.h"

int main(void) {
    printf("#define FILTER_ABI_SIZEOF_FILTER_T %zu\n", sizeof(filter_t));
    printf("#define FILTER_ABI_SIZEOF_FILTER_INPUT_T %zu\n", sizeof(filter_input_t));
    printf("#define FILTER_ABI_SIZEOF_FILTER_OUTPUT_T %zu\n", sizeof(filter_output_t));
    printf("#define FILTER_ABI_SIZEOF_FILTER_SAFETY_CONFIG_T %zu\n", sizeof(filter_safety_config_t));
    printf("#define FILTER_ABI_OFF_UPDATE %zu\n", offsetof(filter_t, update));
    printf("#define FILTER_ABI_OFF_RESET %zu\n", offsetof(filter_t, reset));
    printf("#define FILTER_ABI_OFF_SET_PARAM %zu\n", offsetof(filter_t, set_param));
    printf("#define FILTER_ABI_OFF_TYPE %zu\n", offsetof(filter_t, type));
    printf("#define FILTER_ABI_OFF_DEGRADE %zu\n", offsetof(filter_t, degrade));
    printf("#define FILTER_ABI_OFF_PRIV %zu\n", offsetof(filter_t, priv));
    printf("#define FILTER_ABI_OFF_SAFETY_CONFIG %zu\n", offsetof(filter_t, safety_config));
    printf("#define FILTER_ABI_FILTER_TYPE_COUNT %d\n", (int)FILTER_TYPE_COUNT);
    printf("#define FILTER_ABI_FILTER_DEGRADE_COUNT %d\n", (int)FILTER_DEGRADE_COUNT);
    printf("#define FILTER_ABI_FILTER_PARAM_COUNT %d\n", (int)FILTER_PARAM_COUNT);
    printf("#define FILTER_ABI_API_VERSION %d\n", FILTER_API_VERSION);
    return 0;
}
'''


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    inc_dir = os.path.join(project_root, "Core", "Filter", "Inc")
    test_dir = os.path.join(project_root, "test")

    # 写入临时探测文件
    probe_path = os.path.join(test_dir, "_abi_probe.c")
    exe_path = os.path.join(test_dir, "_abi_probe.exe")

    with open(probe_path, "w") as f:
        f.write(PROBE_C)

    # 编译探测程序
    cc = os.environ.get("CC", "gcc")
    cmd = [
        cc, "-o", exe_path, probe_path,
        f"-I{inc_dir}", "-lm"
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: compilation failed:\n{e.stderr}", file=sys.stderr)
        sys.exit(1)

    # 运行探测程序
    result = subprocess.run([exe_path], check=True, capture_output=True, text=True)
    output = result.stdout.strip()

    # 生成 abi_expected.h
    header_path = os.path.join(inc_dir, "abi_expected.h")
    with open(header_path, "w") as f:
        f.write(f"/* Auto-generated by scripts/gen_abi_header.py — DO NOT EDIT on branches */\n")
        f.write(f"/* Run: python3 scripts/gen_abi_header.py */\n\n")
        f.write(f"#ifndef ABI_EXPECTED_H\n#define ABI_EXPECTED_H\n\n")
        f.write(output + "\n\n")
        f.write(f"#endif /* ABI_EXPECTED_H */\n")

    print(f"Generated: {header_path}")
    print(f"Contents:\n{output}")

    # 清理临时文件
    os.remove(probe_path)
    os.remove(exe_path)


if __name__ == "__main__":
    main()
